	"recid":{$data[no].recid}
	,"reg_date":{$data[no].reg_date}
	,"reg_user_id":{$data[no].reg_user_id}
	,"upd_date":{$data[no].upd_date}
	,"upd_user_id":{$data[no].upd_user_id}
	,"bankid":{$data[no].bankid}
	,"bank_name":{$data[no].bank_name}
	,"bank_no":{$data[no].bank_no}
	,"receipt_bankid":{$data[no].receipt_bankid}
	,"receipt_bank_name":{$data[no].receipt_bank_name}
	,"receipt_bank_no":{$data[no].receipt_bank_no}
	,"reg_stat":{$data[no].reg_stat}
	,"reg_stat_name":{$data[no].reg_stat_name}
	,"hla_a1":{$data[no].hla_a1}
	,"hla_a1_name":{$data[no].hla_a1_name}
	,"hla_a2":{$data[no].hla_a2}
	,"hla_a2_name":{$data[no].hla_a2_name}
	,"hla_b1":{$data[no].hla_b1}
	,"hla_b1_name":{$data[no].hla_b1_name}
	,"hla_b2":{$data[no].hla_b2}
	,"hla_b2_name":{$data[no].hla_b2_name}
	,"hla_cw1":{$data[no].hla_cw1}
	,"hla_cw1_name":{$data[no].hla_cw1_name}
	,"hla_cw2":{$data[no].hla_cw2}
	,"hla_cw2_name":{$data[no].hla_cw2_name}
	,"hla_dr1":{$data[no].hla_dr1}
	,"hla_dr1_name":{$data[no].hla_dr1_name}
	,"hla_dr2":{$data[no].hla_dr2}
	,"hla_dr2_name":{$data[no].hla_dr2_name}
	,"hla_dq1":{$data[no].hla_dq1}
	,"hla_dq1_name":{$data[no].hla_dq1_name}
	,"hla_dq2":{$data[no].hla_dq2}
	,"hla_dq2_name":{$data[no].hla_dq2_name}
	,"a_1":{$data[no].a_1}
	,"a_1_name":{$data[no].a_1_name}
	,"a_2":{$data[no].a_2}
	,"a_2_name":{$data[no].a_2_name}
	,"b_1":{$data[no].b_1}
	,"b_1_name":{$data[no].b_1_name}
	,"b_2":{$data[no].b_2}
	,"b_2_name":{$data[no].b_2_name}
	,"c_1":{$data[no].c_1}
	,"c_1_name":{$data[no].c_1_name}
	,"c_2":{$data[no].c_2}
	,"c_2_name":{$data[no].c_2_name}
	,"drb1_1":{$data[no].drb1_1}
	,"drb1_1_name":{$data[no].drb1_1_name}
	,"drb1_2":{$data[no].drb1_2}
	,"drb1_2_name":{$data[no].drb1_2_name}
	,"dqb1_1":{$data[no].dqb1_1}
	,"dqb1_1_name":{$data[no].dqb1_1_name}
	,"dqb1_2":{$data[no].dqb1_2}
	,"dqb1_2_name":{$data[no].dqb1_2_name}
	,"collect_date":{$data[no].collect_date}
	,"blood_abo":{$data[no].blood_abo}
	,"blood_rh":{$data[no].blood_rh}
	,"sex":{$data[no].sex}
	,"sex_name":{$data[no].sex_name}
	,"separate_method":{$data[no].separate_method}
	,"freezing_method":{$data[no].freezing_method}
	,"protect_liq":{$data[no].protect_liq}
	,"preserve_vol":{$data[no].preserve_vol}
	,"preserve_temp":{$data[no].preserve_temp}
	,"cell_num":{$data[no].cell_num}
	,"cd34_num":{$data[no].cd34_num}
	,"cd34_method":{$data[no].cd34_method}
	,"cfu_num":{$data[no].cfu_num}
	,"cfugm_num":{$data[no].cfugm_num}
	,"cfugm_method":{$data[no].cfugm_method}
	,"cmvigm_method":{$data[no].cmvigm_method}
	,"cmvdna_method":{$data[no].cmvdna_method}
	,"note":{$data[no].note}
	,"supply_date":{$data[no].supply_date}
	,"supply_hosp":{$data[no].supply_hosp}
	,"trans_date":{$data[no].trans_date}
	,"trans_flag":{$data[no].trans_flag}
	,"hosp_code":{$data[no].hosp_code}
	,"hosp_name":{$data[no].hosp_name}
	,"rbc_rate":{$data[no].rbc_rate}
	,"caseid":{$data[no].caseid}
	,"trump_hosp_code":{$data[no].trump_hosp_code}
	,"trump_hosp_name":{$data[no].trump_hosp_name}
	,"harvest_cell_num":{$data[no].harvest_cell_num}
	,"harvest_preserve_vol":{$data[no].harvest_preserve_vol}
