<?php
    const $a = "INSERT INTO public.state( 
        sysid,
        opeid,
        sys_mode,
        recid,
        sys_date,
        sys_user_id,
        reg_date,
        reg_user_id,
        upd_date,
        upd_user_id,
        del_flg,
        recipid,
        cordid,
        reg_stat,
        user_id,
        reserve_date,
        cancel_date,
        supply_date,
        supply_hosp,
        hosp_code,
        rank,
        userid,
        cocktail,
        search_number,
        fit_number,
        note) VALUES (
            1,
            1,
            1,
            1,
            '2019/07/24 15:07:06',
            1,
            '2019/07/24 15:07:06',
            1, 
            '2019/07/24 15:07:06',
            0,
            1,
            1,
            1,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null);"

$b = "insert into state(recipid,cordid,reg_stat,user_id,
reserve_date,cancel_date,supply_date,supply_hosp,hosp_code,rank,userid,cocktail,
search_number,fit_number,note,sysid,opeid,sys_mode,recid,sys_date,sys_user_id,reg_date,
reg_user_id,upd_date,upd_user_id,del_flg) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
?>